{% set name = "domb-napari" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/domb_napari-{{ version }}.tar.gz
  sha256: 33553b0edb98624dd7e7cdb026a5d120b72d122c083c1bbc78b27f97a9c6f3fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dipy
    - domb
    - matplotlib-base
    - napari
    - numpy
    - plotly
    - python >={{ python_min }}
    - scikit-image
    - scipy
    - vispy

test:
  imports:
    - domb_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/domb-napari
  summary: Napari plugin implementing DoMB Tools for analyzing fluorescence-labeled proteins redistribution
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/wisstock/domb-napari

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - wisstock
